### ISSUE TITLE
Issue with estimateCellCounts2()

### ISSUE THREAD

**Issue by hayleywelsh** [immunomethylomics/FlowSorted.Blood.EPIC#11]
The estimateCellCounts2() function is consistently giving me the warning message: ```In asMethod(object) : NAs introduced by coercion```

I have included the workflow below:
```> library(FlowSorted.Blood.EPIC)
> library(ExperimentHub)  
> hub <- ExperimentHub()
snapshotDate(): 2024-04-29
> query(hub, "FlowSorted.Blood.EPIC")  
ExperimentHub with 1 record
# snapshotDate(): 2024-04-29
# names(): EH1136
# package(): FlowSorted.Blood.EPIC
# $dataprovider: GEO
# $species: Homo sapiens
# $rdataclass: RGChannelSet
# $rdatadateadded: 2018-04-20
# $title: FlowSorted.Blood.EPIC: Illumina Human Methylation data from EPIC on immunomagnetic sorted adult blood cell populations
# $description: The FlowSorted.Blood.EPIC package contains Illumina HumanMethylationEPIC (<93>EPIC<94>)) DNA methylation microarray data from th...
# $taxonomyid: 9606
# $genome: hg19
# $sourcetype: tar.gz
# $sourceurl: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE110554
# $sourcesize: NA
# $tags: c("ExperimentData", "Homo_sapiens_Data", "Tissue", "MicroarrayData", "Genome", "TissueMicroarrayData",
#   "MethylationArrayData") 
# retrieve record with 'object[["EH1136"]]' 
> FlowSorted.Blood.EPIC <- hub[["EH1136"]]  
see ?FlowSorted.Blood.EPIC and browseVignettes('FlowSorted.Blood.EPIC') for documentation
loading from cache
> # RGset includes all probes
> # Using author recommended processing method (Noob) and IDOL 
> countsEPIC<-estimateCellCounts2(RGset, compositeCellType = "Blood", processMethod = "preprocessNoob",  probeSelect = "IDOL",  cellTypes = c("CD8T", "CD4T", "NK", "Bcell",  "Mono", "Neu"),  referencePlatform = "IlluminaHumanMethylationEPIC",  referenceset = NULL,  IDOLOptimizedCpGs =IDOLOptimizedCpGs,   returnAll = FALSE)  
snapshotDate(): 2024-04-29
snapshotDate(): 2024-04-29
see ?FlowSorted.Blood.EPIC and browseVignettes('FlowSorted.Blood.EPIC') for documentation
loading from cache
[estimateCellCounts2] Combining user data with reference (flow sorted) data.
[estimateCellCounts2] Processing user and reference data together.
[estimateCellCounts2] Using IDOL L-DMR probes for composition estimation.
[estimateCellCounts2] Estimating proportion composition (prop), if you provide cellcounts those will be provided as counts in the composition estimation.
Warning message:
In asMethod(object) : NAs introduced by coercion
> dim(countsEPIC$counts)
NULL
```

I saw a similar issue posted before and did some of the relevant diagnostic test (see below) but everything seems as if it should be running fine. 

```> head(pData(RGset))
DataFrame with 6 rows and 12 columns
                    Sample_Name Sample_Group Sample_Plate     Project     Pool_ID Sample_Well Unique_Sample_Name    Ind_Name       Array
                    <character>    <integer>  <character> <character> <character> <character>        <character> <character> <character>
205059630043_R01C01  BI100126_1            1            1    PAR17829           0         A01      P1_BI100126_1    BI100126      R01C01
205059630043_R02C01  BI100126_2            2            1    PAR17829           0         B01      P1_BI100126_2    BI100126      R02C01
205059630043_R03C01  BI100141_1            1            1    PAR17829           0         C01      P1_BI100141_1    BI100141      R03C01
205059630043_R04C01  BI100141_2            2            1    PAR17829           0         D01      P1_BI100141_2    BI100141      R04C01
205059630043_R05C01  BI100202_1            1            1    PAR17829           0         E01      P1_BI100202_1    BI100202      R05C01
205059630043_R06C01  BI100202_2            2            1    PAR17829           0         F01      P1_BI100202_2    BI100202      R06C01
                           Slide               Basename              filenames
                     <character>            <character>            <character>
205059630043_R01C01 205059630043 E:/welsh/SABE-Methyl.. E:/welsh/SABE-Methyl..
205059630043_R02C01 205059630043 E:/welsh/SABE-Methyl.. E:/welsh/SABE-Methyl..
205059630043_R03C01 205059630043 E:/welsh/SABE-Methyl.. E:/welsh/SABE-Methyl..
205059630043_R04C01 205059630043 E:/welsh/SABE-Methyl.. E:/welsh/SABE-Methyl..
205059630043_R05C01 205059630043 E:/welsh/SABE-Methyl.. E:/welsh/SABE-Methyl..
205059630043_R06C01 205059630043 E:/welsh/SABE-Methyl.. E:/welsh/SABE-Methyl..
> !"CellType" %in% names(colData(FlowSorted.Blood.EPIC)) #FALSE 
[1] FALSE
> !"CellType" %in% names(colData(RGset)) #TRUE 
[1] TRUE
> FlowSorted.Blood.EPIC
class: RGChannelSet 
dim: 1051815 49 
metadata(0):
assays(2): Green Red
rownames(1051815): 1600101 1600111 ... 99810990 99810992
rowData names(0):
colnames(49): 201868500150_R01C01 201868500150_R03C01 ... 201870610111_R06C01 201870610111_R07C01
colData names(32): Sample_Plate Sample_Well ... filenames normalmix
Annotation
  array: IlluminaHumanMethylationEPIC
  annotation: ilm10b4.hg19
```
The only potential issue is saw was that the CpGs in the IDOLOptimizedCpGs list doesn't seem to match the RGset. However, I receive the error message even when I do not include the IDOLOptimizedCpGs. 

```
> commonCpGs <- intersect(rownames(RGset), IDOLOptimizedCpGs)
> length(commonCpGs)
[1] 0
```

**Comment by lucassalas** [comment]
Hi @***@***.***>,

I believe you are confused about the objects. First you need the proportions instead of the counts (unless you are providing cell counts to estimate those numbers. Please use the countsEPIC$prop to obtain the proportions. Please see the help file to understand this.

To your second question the RGChannelSet have addresses not "cg" illumina probes so the overlap will be zero.

I hope that answers your questions.

Best,

Lucas

From: hayleywelsh ***@***.***>
Sent: Monday, September 9, 2024 10:48 AM
To: immunomethylomics/FlowSorted.Blood.EPIC ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [immunomethylomics/FlowSorted.Blood.EPIC] Issue with estimateCellCounts2() (Issue #11)


The estimateCellCounts2() function is consistently giving me the warning message: In asMethod(object) : NAs introduced by coercion

I have included the workflow below:

> library(ExperimentHub)

> hub <- ExperimentHub()

snapshotDate(): 2024-04-29

> query(hub, "FlowSorted.Blood.EPIC")

ExperimentHub with 1 record

# snapshotDate(): 2024-04-29

# names(): EH1136

# package(): FlowSorted.Blood.EPIC

# $dataprovider: GEO

# $species: Homo sapiens

# $rdataclass: RGChannelSet

# $rdatadateadded: 2018-04-20

# $title: FlowSorted.Blood.EPIC: Illumina Human Methylation data from EPIC on immunomagnetic sorted adult blood cell populations

# $description: The FlowSorted.Blood.EPIC package contains Illumina HumanMethylationEPIC (<93>EPIC<94>)) DNA methylation microarray data from th...

# $taxonomyid: 9606

# $genome: hg19

# $sourcetype: tar.gz

# $sourceurl: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE110554

# $sourcesize: NA

# $tags: c("ExperimentData", "Homo_sapiens_Data", "Tissue", "MicroarrayData", "Genome", "TissueMicroarrayData",

#   "MethylationArrayData")

# retrieve record with 'object[["EH1136"]]'

> FlowSorted.Blood.EPIC <- hub[["EH1136"]]

see ?FlowSorted.Blood.EPIC and browseVignettes('FlowSorted.Blood.EPIC') for documentation

loading from cache

> # RGset includes all probes

> # Using author recommended processing method (Noob) and IDOL

> countsEPIC<-estimateCellCounts2(RGset, compositeCellType = "Blood", processMethod = "preprocessNoob",  probeSelect = "IDOL",  cellTypes = c("CD8T", "CD4T", "NK", "Bcell",  "Mono", "Neu"),  referencePlatform = "IlluminaHumanMethylationEPIC",  referenceset = NULL,  IDOLOptimizedCpGs =IDOLOptimizedCpGs,   returnAll = FALSE)

snapshotDate(): 2024-04-29

snapshotDate(): 2024-04-29

see ?FlowSorted.Blood.EPIC and browseVignettes('FlowSorted.Blood.EPIC') for documentation

loading from cache

[estimateCellCounts2] Combining user data with reference (flow sorted) data.

[estimateCellCounts2] Processing user and reference data together.

[estimateCellCounts2] Using IDOL L-DMR probes for composition estimation.

[estimateCellCounts2] Estimating proportion composition (prop), if you provide cellcounts those will be provided as counts in the composition estimation.

Warning message:

In asMethod(object) : NAs introduced by coercion

> dim(countsEPIC$counts)

NULL

I saw a similar issue posted before and did some of the relevant diagnostic test (see below) but everything seems as if it should be running fine.

DataFrame with 6 rows and 12 columns

                    Sample_Name Sample_Group Sample_Plate     Project     Pool_ID Sample_Well Unique_Sample_Name    Ind_Name       Array

                    <character>    <integer>  <character> <character> <character> <character>        <character> <character> <character>

205059630043_R01C01  BI100126_1            1            1    PAR17829           0         A01      P1_BI100126_1    BI100126      R01C01

205059630043_R02C01  BI100126_2            2            1    PAR17829           0         B01      P1_BI100126_2    BI100126      R02C01

205059630043_R03C01  BI100141_1            1            1    PAR17829           0         C01      P1_BI100141_1    BI100141      R03C01

205059630043_R04C01  BI100141_2            2            1    PAR17829           0         D01      P1_BI100141_2    BI100141      R04C01

205059630043_R05C01  BI100202_1            1            1    PAR17829           0         E01      P1_BI100202_1    BI100202      R05C01

205059630043_R06C01  BI100202_2            2            1    PAR17829           0         F01      P1_BI100202_2    BI100202      R06C01

                           Slide               Basename              filenames

                     <character>            <character>            <character>

205059630043_R01C01 205059630043 E:/welsh/SABE-Methyl.. E:/welsh/SABE-Methyl..

205059630043_R02C01 205059630043 E:/welsh/SABE-Methyl.. E:/welsh/SABE-Methyl..

205059630043_R03C01 205059630043 E:/welsh/SABE-Methyl.. E:/welsh/SABE-Methyl..

205059630043_R04C01 205059630043 E:/welsh/SABE-Methyl.. E:/welsh/SABE-Methyl..

205059630043_R05C01 205059630043 E:/welsh/SABE-Methyl.. E:/welsh/SABE-Methyl..

205059630043_R06C01 205059630043 E:/welsh/SABE-Methyl.. E:/welsh/SABE-Methyl..

> !"CellType" %in% names(colData(FlowSorted.Blood.EPIC)) #FALSE

[1] FALSE

> !"CellType" %in% names(colData(RGset)) #TRUE

[1] TRUE

> FlowSorted.Blood.EPIC

class: RGChannelSet

dim: 1051815 49

metadata(0):

assays(2): Green Red

rownames(1051815): 1600101 1600111 ... 99810990 99810992

rowData names(0):

colnames(49): 201868500150_R01C01 201868500150_R03C01 ... 201870610111_R06C01 201870610111_R07C01

colData names(32): Sample_Plate Sample_Well ... filenames normalmix

Annotation

  array: IlluminaHumanMethylationEPIC

  annotation: ilm10b4.hg19

The only potential issue is saw was that the CpGs in the IDOLOptimizedCpGs list doesn't seem to match the RGset. However, I receive the error message even when I do not include the IDOLOptimizedCpGs.

> commonCpGs <- intersect(rownames(RGset), IDOLOptimizedCpGs)

> length(commonCpGs)

[1] 0

-

**Comment by hayleywelsh** [comment]
Hi @lucassalas 

My apologies I am trying to replicate a colleague's code. This is the next set of code provided:
```
out.cell.prop=data.frame(countsEPIC$counts)
out.cell.prop$Sample=rownames(out.cell.prop)
head(out.cell.prop)
``` 
However, when I run the code the row lengths are 0.

```
> out.cell.prop=data.frame(countsEPIC$counts)
> out.cell.prop$Sample=rownames(out.cell.prop)
> head(out.cell.prop)
[1] countsEPIC.counts Sample           
<0 rows> (or 0-length row.names)
```

I just want to confirm that I should instead be using: ```out.cell.prop=data.frame(countsEPIC$prop)```

Thank you!

**Comment by lucassalas** [comment]
That is what would make sense to me. We changed the names a long time ago to avoid confusion about counts and proportions.

But maybe you should reach out to the person providing the code.

Lucas
