### ISSUE TITLE
Error in estimateCellCounts2

### ISSUE THREAD

**Issue by debangana234** [immunomethylomics/FlowSorted.Blood.EPIC#12]
I have idat files for a EPIC array reference dataset from purified blood samples. I generated an RGsetReference from the reference idats and I obtained the RGset object from the idats of the dataset on which I want to perform the deconvolution. Now I am trying to estimate the cell proportions in the latter dataset with using the former dataset as a reference :
`cellCounts <- estimateCellCounts2(
  RGset,
  compositeCellType = "Blood",
  #probeSelect = "IDOL",
  cellTypes = c("CD14","CD16MACS","CD19Naive","CD4Mem","CD4Naive","CD4Th17","CD4Treg","CD8","CD8Mem","CD8Naive","cDC","Eosinophils","IgD-mem","Neutrophils","NK","pDC","Plasmablast"),
  referencePlatform = "IlluminaHumanMethylationEPIC",
  RGsetReference)`
  
  This results in the following error:
  
  `Error in estimateCellCounts2(RGset, compositeCellType = "Blood", cellTypes = c("CD14",  : 
  all elements of argument 'cellTypes' needs to be part of the reference phenoData columns 'CellType' (containg the following elements: '')`
  
  The names of the celltypes provided in the argument list of estimateCellCounts2 are all present in the cellType column of the phenodata:
  `unique(phenoData$cellType)
 [1] "CD14"        "CD16MACS"    "CD19Naive"   "CD4Mem"      "CD4Naive"    "CD4Th17"    
 [7] "CD4Treg"     "CD8"         "CD8Mem"      "CD8Naive"    "cDC"         "Eosinophils"
[13] "IgD-mem"     "Neutrophils" "NK"          "pDC"         "Plasmablast"`

**Comment by lucassalas** [comment]
Hi @debangana234,

I have a few clarifying points to ensure we're aligned. Please note that all vectors used in this process are **case-sensitive**, so the output you're showing doesn't match what the program expects.

**Key clarifications**:
The **phenoData** (or **pData**) is a slot in the Red-Green Channel Set object from minfi (i.e., RGChannelSet or RGChannelSetExtended objects). It is not an independent object.
You need to test the following code:
`
dput(levels(as.factor(pData(RGsetReference)$CellType)))
`
This should match the levels you're passing in the cellTypes argument of estimateCellCounts2. My guess for your case is that it might look something like this: 

`
c("CD14", "CD16MACS", "CD19Naive", "CD4Mem", "CD4Naive", "CD4Th17", "CD4Treg", "CD8", "CD8Mem", "CD8Naive", "cDC", "Eosinophils", "IgD-mem", "Neutrophils", "NK", "pDC", "Plasmablast")
`
**Custom Deconvolution**
For performing a custom deconvolution, here’s what you need to do:

Run the _traditional model_ to estimate the most differentially methylated sites for your reference set.

If you already have a library selected (for instance, if you’re using the **CustomCpGs** option), you can use that directly. Otherwise, use the code snippet below. Make sure to check the help file (**?estimateCellCounts2**) for further details on using quotes and probeSelect.

```
cellCounts <- estimateCellCounts2(
  RGset, 
  compositeCellType = "Blood", 
  probeSelect = "auto", 
  cellTypes = dput(levels(as.factor(pData(RGsetReference)$CellType))), 
  referenceset = "RGsetReference"
)
```
This should guide you through the custom deconvolution process. Let me know if you need further clarification!

Best,
Lucas

**Comment by debangana234** [comment]
Hello @lucassalas ,
```
cell_types <- levels(as.factor(pData(RGsetReference)$CellType))

cellCounts <- estimateCellCounts2(
  RGset, 
  compositeCellType = "Blood", 
  probeSelect = "IDOL",
  cellTypes = cell_types, 
  referenceset = "RGsetReference"
)

```
This works perfectly now. Thank you very much! :)
