### ISSUE TITLE
Integrate with minfi

### ISSUE THREAD

**Issue by demis001** [immunomethylomics/FlowSorted.Blood.EPIC#2]
@immunomethlomics

I am trying to use this package with minfi.  In 450k package, I do this line to estimate the cell type count. 

`counts <- estimateCellCounts(rgset,compositeCellType = "Blood",cellTypes=c("CD8T","CD4T", "NK","Bcell","Mono","Gran")) `

Would you please help how to replicate the above line with this package with EPIC chip? This is my first time to deal with 850k data. I have followed the Vignettes of the package but never succeeded.

The `rgset` object is shown below:

```
> rgset
class: RGChannelSet 
dim: 1051815 96 
metadata(0):
assays(2): Green Red
rownames(1051815): 1600101 1600111 ... 99810990 99810992
rowData names(0):
colnames(96): 6 30 ... 11542 2133-2
colData names(228): Sample_Name Sentrix_ID ... NAFLD_DX.Method exclude_epi
Annotation
  array: IlluminaHumanMethylationEPIC
  annotation: ilm10b4.hg19
```

Best,
@demis001

**Comment by lucassalas** [comment]
Hi @demis001 ,
You have already your RGChannelSet. So please first check that you have either pData(rgset)$Age or pData(rgset)$Sex on your dataset. This is important during the combineArrays step of the function if you do not have at least two common variables this step will crash.

Please use estimateCellCounts2 instead of minfi. This is just a derived function that allows calling any reference (custom or one in ExperimentHub) for cell deconvolution.

Run the following:
```
library(FlowSorted.Blood.EPIC)
library(ExperimentHub)
hub <- ExperimentHub()
query(hub, "FlowSorted.Blood.EPIC")
FlowSorted.Blood.EPIC <- hub[["EH1136"]]
FlowSorted.Blood.EPIC

countsEPIC<-estimateCellCounts2(RGsetTargets, compositeCellType = "Blood", 
                                processMethod = "preprocessNoob",
                                probeSelect = "IDOL", 
                                cellTypes = c("CD8T", "CD4T", "NK", "Bcell", 
                                "Mono", "Neu"), 
                                referencePlatform = 
                                "IlluminaHumanMethylationEPIC",
                                referenceset = NULL,
                                IDOLOptimizedCpGs =IDOLOptimizedCpGs, 
                                returnAll = FALSE)
                                
head(countsEPIC$counts)

counts<-countsEPIC$counts

```

Notice two things:

1. There are no Granulocytes but Neutrophils in the library. So you should specify "Neu" instead. 
2. If you cannot access internet from your machine for calling the ExperimentHub step. You can save the object locally and replace referenceset = FlowSorted.Blood.EPIC or the name that you saved the database.

Let me know whether that is clear to close this threat.

Best,
@lucassalas
